channels:
- conda-forge
dependencies:
- flask=1.1.2
- flask-wtf=0.14.3
- pandas=1.1.4
- python=3.7.8
- uwsgi=2.0.19.1
- xlrd=1.2.0
- xlsxwriter=1.3.7
- openpyxl=3.0.5
- redis-py=3.5.3
- pyarrow=2.0.0
- pymongo=3.11.0
- scikit-learn=0.23.2
- numba=0.52.0
