version: '3'
services:
  mongo:
    restart: unless-stopped
  flask_app:
    restart: unless-stopped
  nginx:
    build: nginx
    restart: unless-stopped
    ports:
     - 8080:8080
    depends_on:
     - flask_app
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  backup:
    build:
      context: ./backup
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ../../FactorStrategyAppBackups:/backups
    depends_on:
      - mongo
